// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIkSmI3VgRqiN3GHehb6LoepLClPWwKkI',
    appId: '1:674664469055:web:bab51ca9f8f4c2d81a9e8a',
    messagingSenderId: '674664469055',
    projectId: 'sprout-60aa1',
    authDomain: 'sprout-60aa1.firebaseapp.com',
    storageBucket: 'sprout-60aa1.firebasestorage.app',
    measurementId: 'G-Y9HGNRD1ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6cftN0WhSpkXY-Uz7FAV-1e5pWGLcTM',
    appId: '1:674664469055:android:58206b2fd8a944af1a9e8a',
    messagingSenderId: '674664469055',
    projectId: 'sprout-60aa1',
    storageBucket: 'sprout-60aa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc8oWRinnTdg4C7ZFStKTJc1siCsvQ2MU',
    appId: '1:674664469055:ios:83d22500107d3a471a9e8a',
    messagingSenderId: '674664469055',
    projectId: 'sprout-60aa1',
    storageBucket: 'sprout-60aa1.firebasestorage.app',
    iosBundleId: 'com.example.spring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc8oWRinnTdg4C7ZFStKTJc1siCsvQ2MU',
    appId: '1:674664469055:ios:83d22500107d3a471a9e8a',
    messagingSenderId: '674664469055',
    projectId: 'sprout-60aa1',
    storageBucket: 'sprout-60aa1.firebasestorage.app',
    iosBundleId: 'com.example.spring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIkSmI3VgRqiN3GHehb6LoepLClPWwKkI',
    appId: '1:674664469055:web:2458d7f26568b8d41a9e8a',
    messagingSenderId: '674664469055',
    projectId: 'sprout-60aa1',
    authDomain: 'sprout-60aa1.firebaseapp.com',
    storageBucket: 'sprout-60aa1.firebasestorage.app',
    measurementId: 'G-P5R859SVJV',
  );
}
